#!/bin/sh
if [ -z $1 ]
then
    echo "No parameter passed"
    echo "Usage: ./node mainnet node1"
    echo "Usage: ./node mainnet node2"
    echo "Usage: ./node testnet node3"
    exit
else
    echo "Chain: $1"
fi
chain=$1

if [ -z $2 ]
then
    echo "No second parameter passed"
    exit
else
    echo "Node service: $2"
fi
service=$2

if [ "$chain" = "testnet" ]
then
  docker compose -f docker-compose-test-cnode.yml up $service -d
else
  echo "Invalid config parameter"
  exit
fi
